site_name: B-FAST Documentação
site_url: https://marcelomarkus.github.io/b-fast/pt/
docs_dir: docs

theme:
  name: material
  palette:
    scheme: slate
    primary: teal
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
  language: pt

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [../../python]

nav:
  - Início: index.md
  - Começando: getting_started.md
  - Frontend: frontend.md
  - Performance: performance.md
  - Solução de Problemas: troubleshooting.md

extra:
  alternate:
    - name: English
      link: /b-fast/
      lang: en
    - name: Português
      link: /b-fast/pt/
      lang: pt
